---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: rootca
    box: jtarpley/${MOLECULE_BOX:-w2022_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: adcs_sub_ca_certificate_
    groups:
      - windows
  - name: win
    box: jtarpley/${MOLECULE_OS:-w2022_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: adcs_sub_ca_certificate_
    groups:
      - subjects
      - windows
provisioner:
  name: ansible
  inventory:
    group_vars:
      windows:
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: SYSTEM
    host_vars:
      rootca:
        winca_install_management_tools: true
        winca_is_root_ca: true
        winca_is_ad_integrated: false
        winca_username: vagrant
        winca_password: vagrant
        winca_ca_cert_common_name: RootCA
      win:
        winsubca_ca_common_name: SubCA
        winsubca_ca_distinguished_name_suffix: DC=test,DC=local
        winsubca_signing_ca_hostname: rootca
        winsubca_signing_ca_fqdn: rootca
        winsubca_signing_ca_common_name: RootCA
verifier:
  name: ansible
