---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: rootca
    box: "jtarpley/${MOLECULE_OS:-w2022}_cis"
    memory: 2048
    cpus: 2
  - name: win
    box: "jtarpley/${MOLECULE_OS:-w2022}_cis"
    memory: 2048
    cpus: 2
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ./hosts
      host_vars: ./host_vars/
      group_vars: ./group_vars/
verifier:
  name: ansible
