---
winsubca_renewal_days: 30

winsubca_request_config_file_temp_path: C:\Windows\temp\cacert.inf
winsubca_request_file_temp_path: C:\Windows\temp\cacert.req
winsubca_signing_ca_cert_file_temp_path: C:\Windows\temp\signingcacert.crt
winsubca_cert_file_temp_path: C:\Windows\temp\cacert.crt

winsubca_signing_ca_fqdn: "{{ hostvars[winsubca_signing_ca_hostname].ansible_fqdn }}"
winsubca_signing_ca_config: "{{ winsubca_signing_ca_fqdn }}\\{{ winsubca_signing_ca_common_name }}"
winsubca_rootca_file_path: "C:\\Windows\\system32\\CertSrv\\CertEnroll\\{{ winsubca_signing_ca_fqdn }}_{{ winsubca_signing_ca_common_name }}.crt"
winsubca_cert_line_break_character: "\r\n"
