---
namespace: trippsc2
name: adcs
version: 1.2.1
readme: README.md
authors:
  - Jim Tarpley
description: This collection contains modules and roles for configuring Active Directory Certificate Services.

license_file: 'LICENSE'

tags: []

dependencies:
  ansible.windows: ">=1.0.0"
  community.windows: ">=1.0.0"
  trippsc2.general: ">=2.4.0"
  trippsc2.windows: ">=1.0.0"

repository: https://github.com/trippsc2/ansible-collection-adcs.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
