---
_winca_ca_type_prefix: "{{ 'Enterprise' if winca_is_ad_integrated else 'Standalone' }}"
_winca_ca_type_suffix: "{{ 'RootCA' if winca_is_root_ca else 'SubordinateCA' }}"

_winca_formatted_hash_algorithm_name: "{{ winca_hash_algorithm_name | upper }}"

_winca_ca_type: "{{ _winca_ca_type_prefix }}{{ _winca_ca_type_suffix }}"

_winca_crypto_provider_name: "{{ winca_crypto_provider_name if _winca_certificate_options_needed else omit }}"
_winca_hash_algorithm_name: "{{ _winca_formatted_hash_algorithm_name if _winca_certificate_options_needed else omit }}"
_winca_key_length: "{{ winca_key_length if _winca_certificate_options_needed else omit }}"
_winca_overwrite_existing_key: "{{ winca_overwrite_existing_key if winca_is_root_ca else omit }}"

_winca_enterprise_parent_certificate: >-
  {{ _winca_ca_type == 'EnterpriseSubordinateCA' and winca_certificate_type == 'enterprise_parent' }}

_winca_certificate_options_needed: "{{ winca_is_root_ca or _winca_enterprise_parent_certificate }}"

_winca_ca_cert_common_name: "{{ winca_ca_cert_common_name if _winca_certificate_options_needed else omit }}"
_winca_ca_distinguished_name_suffix: "{{ winca_ca_distinguished_name_suffix | default(omit) if _winca_certificate_options_needed else omit }}"
_winca_ignore_unicode: "{{ winca_ignore_unicode if _winca_certificate_options_needed else omit }}"
_winca_ca_cert_validity_period_unit: "{{ winca_ca_cert_validity_period_unit if winca_is_root_ca else omit }}"
_winca_ca_cert_validity_period: "{{ winca_ca_cert_validity_period if winca_is_root_ca else omit }}"

_winca_parent_ca_config: "{{ winca_parent_ca_config if _winca_enterprise_parent_certificate else omit }}"

_winca_overwrite_existing_ca_in_domain: >-
  {{ winca_overwrite_existing_ca_in_domain | default(omit) if winca_is_ad_integrated else omit }}
