---
- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Sign certificate
  ansible.builtin.import_tasks: sign.yml

- name: Include OS family tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
