---
- name: Copy signed certificate to path
  when:
    - cert_certificate_to_file
    - cert_certificate_content | default('') != ''
  ansible.windows.win_copy:
    content: "{{ cert_certificate_content }}"
    dest: "{{ cert_certificate_path }}"

- name: Clear CSR variable
  ansible.builtin.set_fact:
    cert_csr_content: ''
