---
- name: Gather OS Facts
  when:
    - ansible_distribution is not defined or
      ansible_os_family is not defined
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution
      - os_family

- name: Validate Windows Server
  ansible.builtin.assert:
    that:
      - ansible_os_family == 'Windows'
      - ('Windows Server' in ansible_distribution)
    fail_msg: "This role can only be run on a Windows Server system.  {{ ansible_distribution }} is not supported."
    success_msg: "This role is running on {{ ansible_distribution }}."
