---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: sub_ca_certificate
  description: This role signs a subordinate CA certificate on a Windows machine.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Windows
      versions:
        - '2025'
        - '2022'
        - '2019'

collections:
  - ansible.windows
  - community.windows

dependencies: []
