---
cert_certificate_to_file: true
cert_certificate_to_variable: false
cert_certificate_owner: root
cert_certificate_group: root
cert_certificate_mode: '0644'

cert_signing_ca_fqdn: "{{ hostvars[cert_signing_ca_hostname].ansible_fqdn }}"
cert_signing_ca_config: "{{ cert_signing_ca_fqdn }}\\{{ cert_signing_ca_common_name }}"
cert_signing_ca_csr_path: "C:\\Windows\\temp\\{{ inventory_hostname }}.req"
cert_line_break_character: "\n"

cert_csr_to_file: true
