---
winca_is_root_ca: false

winca_ca_cert_common_name: "{{ inventory_hostname }}"
winca_ca_distinguished_name_suffix: DC=test,DC=loc

winsubca_request_config_file_temp_path: "C:\\Windows\\temp\\{{ inventory_hostname }}.inf"
winsubca_request_file_temp_path: "C:\\Windows\\temp\\{{ inventory_hostname }}.req"
winsubca_signing_ca_cert_file_temp_path: C:\Windows\temp\signingcacert.crt
winsubca_cert_file_temp_path: "C:\\Windows\\temp\\{{ inventory_hostname }}.crt"
