---
- name: Verify
  hosts:
    - subjects
  gather_facts: false
  tasks:
    - name: Get private key file info
      ansible.windows.win_stat:
        path: C:\Windows\Temp\cert.key
      register: _private_key_info

    - name: Get certificate file info
      ansible.windows.win_stat:
        path: C:\Windows\Temp\cert.crt
      register: _certificate_info

    - name: Get CSR file info
      ansible.windows.win_stat:
        path: C:\Windows\Temp\cert.csr
      register: _csr_info

    - name: Assert that private key exists
      ansible.builtin.assert:
        that:
          - _private_key_info.stat.exists
        fail_msg: Private key file does not exist
        success_msg: Private key file exists

    - name: Assert that certificate exists
      ansible.builtin.assert:
        that:
          - _certificate_info.stat.exists
        fail_msg: Certificate file does not exist
        success_msg: Certificate file exists

    - name: Assert that CSR file is not present
      ansible.builtin.assert:
        that:
          - not _csr_info.stat.exists
        fail_msg: CSR file still exists
        success_msg: CSR file does not exist, as expected
