---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: ca
    box: jtarpley/w2022_cis
    memory: 2048
    cpus: 2
    groups:
      - windows
  - name: linux
    box: jtarpley/${MOLECULE_BOX:-rocky8_cis}
    memory: 2048
    cpus: 2
    groups:
      - subjects
provisioner:
  name: ansible
  inventory:
    group_vars:
      subjects:
        cert_signing_ca_hostname: ca
        cert_signing_ca_fqdn: ca
        cert_signing_ca_common_name: RootCA
        cert_signing_ca_csr_path: "C:\\Windows\\Temp\\{{ inventory_hostname }}.csr"
      windows:
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: SYSTEM
    host_vars:
      ca:
        winca_install_management_tools: true
        winca_is_root_ca: true
        winca_is_ad_integrated: false
        winca_username: .\vagrant
        winca_password: vagrant
        winca_ca_cert_common_name: RootCA
verifier:
  name: ansible
