---
- name: Prepare certification authority
  hosts:
    - ca
  roles:
    - role: trippsc2.adcs_certification_authority
  tasks:
    - name: Reboot
      ansible.windows.win_reboot:

- name: Prepare Linux
  hosts:
    - linux
  tasks:
    - name: Bootstrap python for Ansible
      become: true
      ansible.builtin.raw: |
        command -v python3 python || (
        command -v apk >/dev/null && sudo apk add --no-progress --update python3 ||
        (test -e /usr/bin/dnf && sudo dnf install -y python3) ||
        (test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal)) ||
        (test -e /usr/bin/yum && sudo yum -y -qq install python3) ||
        (test -e /usr/sbin/pkg && sudo env ASSUME_ALWAYS_YES=yes pkg update && sudo env ASSUME_ALWAYS_YES=yes pkg install python3) ||
        (test -e /usr/sbin/pkg_add && sudo /usr/sbin/pkg_add -U -I -x python%3.7) ||
        echo "Warning: Python not bootstrapped due to unknown platform."
        )
      changed_when: false
