---
- name: Gathering Facts
  when:
    - ansible_distribution is not defined or
      ansible_os_family is not defined or
      ansible_windows_domain_member is not defined
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution
      - os_family
      - windows_domain

- name: Validate Windows Server
  ansible.builtin.assert:
    that:
      - ansible_os_family == 'Windows'
      - ('Windows Server' in ansible_distribution)
    fail_msg: "This role can only be run on a Windows Server system.  {{ ansible_distribution }} is not supported."
    success_msg: "This role is running on {{ ansible_distribution }}."

- name: Validate that the machine is a domain member
  when:
    - winca_is_ad_integrated
  ansible.builtin.assert:
    that:
      - ansible_windows_domain_member
    fail_msg: This machine is not a domain member.
    success_msg: This machine is a domain member.

- name: Include crypto provider algorithm variables
  ansible.builtin.include_vars: "{{ winca_crypto_provider_algorithm }}.yml"

- name: Validate key length
  when:
    - winca_is_root_ca or winca_certificate_type == 'enterprise_parent'
    - winca_key_length is defined
  ansible.builtin.assert:
    that:
      - winca_key_length | int in _winca_allowed_key_lengths
    fail_msg: "Key length for {{ winca_crypto_provider_algorithm | upper }} keys must be one of: {{ _winca_allowed_key_lengths | join(', ') }}"
    success_msg: "{{ winca_crypto_provider_algorithm | upper }} key length of {{ winca_key_length }} is valid."
