---
argument_specs:
  main:
    short_description: Active Directory Certificate Services Signed Certificate
    description:
      - This role generates a self-signed TLS certificate.
      - The role depends on the `trippsc2.general.generate_csr` role to generate a private key and CSR.
      - |
        The role does the following:
          - Runs the `trippsc2.general.generate_csr` role to generate a private key and CSR, if needed.
          - If the private key and CSR are generated, the role signs the CSR with the AD CS certification authority and stores it in the `cert_certificate_content` variable.
          - Optionally, the role will save the certificate to a file.
    author:
      - Jim Tarpley (@trippsc2)
    options:
      cert_signing_ca_hostname:
        type: str
        required: true
        description:
          - The hostname of the Certificate Authority to sign the certificate.
      cert_signing_ca_csr_path:
        type: path
        required: false
        default: "C:\\Windows\\temp\\{{ inventory_hostname }}.req"
        description:
          - The path to the Certificate Signing Request (CSR) file to sign.
      cert_signing_ca_fqdn:
        type: str
        required: false
        default: "{{ hostvars[cert_signing_ca_hostname].ansible_fqdn }}"
        description:
          - The Fully Qualified Domain Name (FQDN) of the Certificate Authority to sign the certificate.
          - This variable is only used if the `cert_signing_ca_config` option is not defined.
      cert_signing_ca_common_name:
        type: str
        required: false
        description:
          - The Common Name (CN) of the Certificate Authority to sign the certificate.
          - This variable is only used if the `cert_signing_ca_config` option is not defined.
      cert_signing_ca_config:
        type: str
        required: false
        default: "{{ cert_signing_ca_fqdn }}\\{{ cert_signing_ca_common_name }}"
        description:
          - The configuration of the Certificate Authority to sign the certificate.
          - This variable is only used if the `cert_signing_ca_fqdn` and `cert_signing_ca_common_name` options are not defined.
      cert_signing_ca_user:
        type: str
        required: false
        description:
          - The username to use when connecting to the Certificate Authority.
          - This overrides the `ansible_user` variable.
      cert_signing_ca_password:
        type: str
        no_log: true
        required: false
        description:
          - The password to use when connecting to the Certificate Authority.
          - This overrides the `ansible_password` variable.
      cert_signing_ca_shell_type:
        type: str
        required: false
        description:
          - The shell to use when connecting to the Certificate Authority.
          - This overrides the `ansible_shell_type` variable.
      cert_line_break_character:
        type: str
        required: false
        default: "\\n"
        description:
          - The line break character to use in the certificate.
      cert_certificate_to_file:
        type: bool
        required: false
        default: true
        description:
          - Whether to save the certificate to a file.
          - If set to `true`, the certificate will be saved to the `cert_certificate_path` path.
      cert_certificate_to_variable:
        type: bool
        required: false
        default: false
        description:
          - Whether to save the certificate to a variable.
          - If set to `true`, the certificate will be saved to the `cert_certificate_content` variable.
      cert_certificate_owner:
        type: str
        required: false
        default: root
        description:
          - The owner of the certificate on Linux systems.
      cert_certificate_group:
        type: str
        required: false
        default: root
        description:
          - The group of the certificate on Linux systems.
      cert_certificate_mode:
        type: str
        required: false
        default: '0644'
        description:
          - The mode of the certificate on Linux systems.
