---
galaxy_info:
  author: Jim Tarpley
  namespace: trippsc2
  role_name: signed_certificate
  description: This role issues a certificate from a AD CS Certification Authority.

  license: MIT

  min_ansible_version: '2.14'

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - '8'
        - '9'
    - name: Windows
      versions:
        - '2019'
        - '2022'
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble

collections:
  - ansible.windows

dependencies:
  - role: trippsc2.general.generate_csr
