---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: signed_certificate
  description: |
    This role generates a self-signed TLS certificate.

    The role depends on the `trippsc2.general.generate_csr` role to generate a private key and CSR.

    The role does the following:
      - Runs the `trippsc2.general.generate_csr` role to generate a private key and CSR, if needed.
      - If the private key and CSR are generated, the role signs the CSR with the AD CS certification authority and stores it in the `cert_certificate_content` variable.
      - Optionally, the role will save the certificate to a file.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - '8'
        - '9'
    - name: Windows
      versions:
        - '2019'
        - '2022'
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble

collections:
  - ansible.windows
  - trippsc2.general

dependencies:
  - role: trippsc2.general.generate_csr
