---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/certificate_authority/.aar_doc.yml
      - roles/certificate_authority/README.md
      - roles/certificate_authority/meta/argument_specs.yml
      - roles/certificate_authority/meta/main.yml
      - roles/signed_certificate/.aar_doc.yml
      - roles/signed_certificate/README.md
      - roles/signed_certificate/meta/argument_specs.yml
      - roles/signed_certificate/meta/main.yml
      - roles/sub_ca_certificate/.aar_doc.yml
      - roles/sub_ca_certificate/README.md
      - roles/sub_ca_certificate/meta/argument_specs.yml
      - roles/sub_ca_certificate/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.adcs'
jobs:
  docs_certificate_authority:
    name: Generate certificate_authority role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.adcs'
      role_name: 'certificate_authority'
  docs_signed_certificate:
    name: Generate signed_certificate role documentation
    permissions:
      contents: write
    needs: docs_certificate_authority
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.adcs'
      role_name: 'signed_certificate'
  docs_sub_ca_certificate:
    name: Generate sub_ca_certificate role documentation
    permissions:
      contents: write
    needs: docs_signed_certificate
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.adcs'
      role_name: 'sub_ca_certificate'
