---
name: Generate Role Docs - sub_ca_certificate role
'on':
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docs-sub_ca_certificate.yml
      - roles/sub_ca_certificate/.aar_doc.yml
      - roles/sub_ca_certificate/meta/argument_specs.yml
      - roles/sub_ca_certificate/meta/main.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-sub_ca_certificate.yml
      - roles/sub_ca_certificate/.aar_doc.yml
      - roles/sub_ca_certificate/meta/argument_specs.yml
      - roles/sub_ca_certificate/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.adcs'
jobs:
  docs:
    name: Generate sub_ca_certificate role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.adcs'
      role_name: 'sub_ca_certificate'
